openapi: 3.0.3
info:
  title: Swagger EventHub - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: np25071984@gmail.com
  license:
    name: MIT
    url: https://github.com/np25071984/event-hub
  version: 0.0.1
paths:
  /calendar/{calendarId}:
    get:
      tags:
        - calendar
      summary: Find calendar by ID
      description: Returns a calendar events
      parameters:
        - name: calendarId
          in: path
          description: ID of calendar to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'
        '400':
          description: Invalid ID supplied
        '404':
          description: Calendar not found
components:
  schemas:
    Calendar:
      type: object
      properties:
        name:
          type: string
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        events:
          type: array
          items:
            anyOf:
              - $ref : '#/components/schemas/Task'
              - $ref : '#/components/schemas/Event'

    Task:
      type: object
      properties:
        type:
          type: string
          enum:
            - "task"
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        description:
          type: string

    Event:
      type: object
      properties:
        type:
          type: string
          enum:
            - "event"
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        title:
          type: string
        description:
          type: string
        location:
          type: string
        attendee:
          type: array
          items:
            type: string